[b/432671467] Add missing Redshift Serverless library
This PR fixes the error: Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/services/redshiftserverless/AWSRedshiftServerlessClientBuilder  that occurs when user tries to connect to Redshift Serverless using IAM credentials instead of password.